In [1]:
import numpy as np
x=np.arange(1,10)
y=np.arange(1,10)
print(x)
print(y)
sum=x+y
print("sum is ", sum)
mul=x*y
sq=x**2
print("Multiplication  is ", mul)
print("square is ", sq)
sqrt=np.sqrt(sq)
print("square root is ",sqrt)
z=np.exp(y)
print(z)
x[0]
x[0:3]
x[0:4]=7
print(x)
y=np.eye(5)
print(y)
z=np.zeros(8)
print(z)
y1=np.ones((7,7))
print(y1)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
sum is  [ 2  4  6  8 10 12 14 16 18]
Multiplication  is  [ 1  4  9 16 25 36 49 64 81]
square is  [ 1  4  9 16 25 36 49 64 81]
square root is  [1. 2. 3. 4. 5. 6. 7. 8. 9.]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
[7 7 7 7 5 6 7 8 9]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
